codecov:
  notify:
    wait_for_ci: true
  require_ci_to_pass: true
comment:
  layout: "diff"
  behavior: default
  require_changes:
  - 1
  show_carryforward_flags: true
coverage:
  status:
    patch: false
    project:
      default:
        target: 0.0
        threshold: 60%
    default_rules:
      flag_coverage_not_uploaded_behavior: include
  precision: 3
  range: "50...100"
  round: down



github_checks:
  annotations: true