on:
  pull_request:
    branches: [ main ]
name: CI
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cclauss/Find-Python-syntax-errors-action@master

  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run Tests
        run: |
          python3 -m pytest --cov ./qmetry_pytest/ tests/unit/
          coveralls --service=github
          bash <(curl -s https://codecov.io/bash)
      - name: Unit Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./report/
          retention-days: 7
      - name: Coverage Report Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage.xml
          retention-days: 7